apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-queue-auth
  namespace: sd-ingestor
spec:
  podIdentity:
    provider: azure-workload
    identityId: 6401c99f-138f-4a0d-95e0-5bda3a5de4c7
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sd-ingestor-worker-scaledobject
  namespace: sd-ingestor
spec:
  scaleTargetRef:
    name: sd-ingestor-worker-deployment
  triggers:
    - type: azure-queue
      metadata:
        queueName: ingestor-job-queue
        accountName: dehwstcomsddev
        queueLength: "5"
        cloud: AzurePublicCloud
        desiredReplicas: "5"
      authenticationRef:
        name: azure-queue-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-ingestor-controller-deployment
  namespace: sd-ingestor
  labels:
    azure.workload.identity/use: "true"
    app: sd-ingestor-controller
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sd-ingestor-controller
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app: sd-ingestor-controller
    spec:
      serviceAccountName: sd-ingestor-service
      containers:
        - name: sd-ingestor-controller
          image: #{{IMAGE}}#
          command: ["poetry"]
          args: ["run", "python", "controller.py"]
          resources:
            requests:
              memory: "1024M"
              cpu: "0.2"
            limits:
              memory: "2048M"
              cpu: "1"
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-auth
                  key: DATABASE_URL
            - name: EOD_INGESTOR_STROAGE_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-auth
                  key: STOCK_DATA_STORAGE_ACCOUNT_NAME
            - name: EOD_INGESTOR_STROAGE_QUEUE
              valueFrom:
                secretKeyRef:
                  name: backend-auth
                  key: STOCK_DATA_STORAGE_ACCOUNT_QUEUE
            - name: FLAG_SMITH_ENVIRONMENT_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-auth
                  key: FLAG_SMITH_ENVIRONMENT_KEY
            - name: STOCK_DATA_STORAGE_FILE_SYSTEM
              valueFrom:
                secretKeyRef:
                  name: backend-auth
                  key: STOCK_DATA_STORAGE_FILE_SYSTEM
            - name: MARKETSTACK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-auth
                  key: MARKETSTACK_API_KEY
          volumeMounts:
            - name: kv-secret-store
              mountPath: "/mnt/backend-auth"
              readOnly: true
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.azure.com/scalesetpriority"
                    operator: In
                    values:
                      - "spot"
      volumes:
        - name: kv-secret-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-sync"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sd-ingestor-controller-cron-scaledobject
  namespace: sd-ingestor
spec:
  scaleTargetRef:
    name: sd-ingestor-controller-deployment
  triggers:
    - type: cron
      metadata:
        timezone: "Europe/London"
        start: "45 * * * *"
        end: "55 * * * *"
        desiredReplicas: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-ingestor-worker-deployment
  namespace: sd-ingestor
  labels:
    app: sd-ingestor-worker
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sd-ingestor-worker
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app: sd-ingestor-worker
    spec:
      serviceAccountName: sd-ingestor-service
      containers:
        - name: sd-ingestor-worker
          image: #{{IMAGE}}#
          command: ["poetry"]
          args: ["run", "python", "worker.py"]
          resources:
            requests:
              memory: "1024M"
              cpu: "0.2"
            limits:
              memory: "2048M"
              cpu: "1"
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-auth
                  key: DATABASE_URL
            - name: EOD_INGESTOR_STROAGE_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-auth
                  key: STOCK_DATA_STORAGE_ACCOUNT_NAME
            - name: EOD_INGESTOR_STROAGE_QUEUE
              valueFrom:
                secretKeyRef:
                  name: backend-auth
                  key: STOCK_DATA_STORAGE_ACCOUNT_QUEUE
            - name: FLAG_SMITH_ENVIRONMENT_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-auth
                  key: FLAG_SMITH_ENVIRONMENT_KEY
            - name: STOCK_DATA_STORAGE_FILE_SYSTEM
              valueFrom:
                secretKeyRef:
                  name: backend-auth
                  key: STOCK_DATA_STORAGE_FILE_SYSTEM
            - name: MARKETSTACK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-auth
                  key: MARKETSTACK_API_KEY
          volumeMounts:
            - name: kv-secret-store
              mountPath: "/mnt/backend-auth"
              readOnly: true
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.azure.com/scalesetpriority"
                    operator: In
                    values:
                      - "spot"
      volumes:
        - name: kv-secret-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-sync"
